### ISSUE TITLE
Markers "ember-index-start…", "ember-index-end…" are visible in ouput

### ISSUE THREAD

**Issue by ahx** [ramybenaroya/ember-index#6]
When using this (during development) it outputs "ember-index-start…" "ember-index-end…" markes before and after the injected content.
I noticed that those markers [used to be rendered HTML comments](https://github.com/ramybenaroya/ember-index/commit/f2ecbb54f027dd4b3c20f6a6780b4ca9a0aab7ec).

**Comment by ramybenaroya** [comment]
These markers are for internal usage and should be deleted ([index.js:118](https://github.com/ramybenaroya/ember-index/blob/master/index.js#L118) & [index.js:126](https://github.com/ramybenaroya/ember-index/blob/master/index.js#L126)).
Can you please create an example app repo so I can reproduce?

**Comment by ahx** [comment]
https://github.com/ahx/ember-index-issue-6
![screen shot 2016-05-17 at 14 45 16](https://cloud.githubusercontent.com/assets/8669/15322637/447fb436-1c3e-11e6-8b91-38bff66c95b2.png)

**Comment by ramybenaroya** [comment]
Fixed in `ember-index@0.2.7`. Your ember-index config object didn't include the [`output`](https://github.com/ramybenaroya/ember-index/wiki/Configuration#output-string) property, which is perfectly fine, but the only problem was that the markers deletion occured [only if `output` is present](https://github.com/ramybenaroya/ember-index/commit/ed95e6a3e4130c3b19cb28d8e8a5e441e033b5d3#diff-168726dbe96b3ce427e7fedce31bb0bcL91).
